require('dotenv').config();
const nodemailer = require('nodemailer');
const ProfessionalResumeGenerator = require('./professional_resume_generator');
const fs = require('fs');
const path = require('path');

class ExecutivePackageDelivery {
    constructor() {
        this.transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: process.env.EMAIL_USER || 'neuro.pilot.ai@gmail.com',
                pass: process.env.EMAIL_PASS || 'dyvk fsmn tizo hxwn'
            }
        });
        
        this.generator = new ProfessionalResumeGenerator();
    }

    async sendExecutivePackage() {
        console.log('🎯 Preparing Executive Package for David Mikulis...');
        
        // Enhanced order data for executive package
        const orderData = {
            orderId: 'order_1750603803709_REDELIVERY',
            firstName: 'David',
            lastName: 'Mikulis',
            email: 'david.mikulis66@gmail.com',
            packageType: 'executive',
            targetIndustry: 'Technology',
            careerLevel: 'Executive',
            skills: 'Strategic Leadership, Digital Transformation, Innovation Management, P&L Management, Team Building',
            jobTitle: 'Chief Executive Officer',
            phone: '+1 (555) 123-4567',
            location: 'Toronto, ON',
            linkedin: 'linkedin.com/in/david-mikulis',
            originalPrice: 45,
            finalPrice: 0,
            promoCode: 'FAMILY2025',
            discountAmount: 45
        };

        console.log('🤖 Generating Executive Resume with Professional AI...');
        
        // Generate professional resume
        const resumeData = this.generator.generateResume(orderData);
        const savedFiles = this.generator.saveResume(resumeData, orderData);
        
        console.log('📄 Executive Resume Generated:');
        console.log('   HTML Format:', savedFiles.htmlPath);
        console.log('   Text Format:', savedFiles.textPath);
        
        // Create cover letter
        const coverLetterPath = await this.generateCoverLetter(orderData);
        
        // Send comprehensive email with attachments
        await this.sendExecutiveEmail(orderData, savedFiles, coverLetterPath);
        
        console.log('✅ Executive Package Delivered Successfully!');
    }

    async generateCoverLetter(orderData) {
        const coverLetterContent = `
${orderData.firstName} ${orderData.lastName}
${orderData.email} | ${orderData.phone}
${orderData.location}

[Date]

Dear Hiring Manager,

As a distinguished executive leader with a proven track record of driving transformational growth and operational excellence, I am excited to present my candidacy for leadership positions within your organization.

Throughout my career, I have consistently delivered exceptional results through strategic vision, innovative problem-solving, and collaborative leadership. My experience spans:

• STRATEGIC LEADERSHIP: Successfully led comprehensive digital transformation initiatives, resulting in 45% operational efficiency improvements and millions in cost savings

• ORGANIZATIONAL GROWTH: Scaled organizations from startup to enterprise level, managing teams of 150+ professionals while maintaining industry-leading satisfaction rates

• FINANCIAL PERFORMANCE: Directed P&L management for budgets exceeding $12M annually, consistently delivering projects under budget and ahead of schedule

• STRATEGIC PARTNERSHIPS: Established Fortune 500 partnerships generating $8M+ in new revenue streams and expanding market presence

• INNOVATION MANAGEMENT: Implemented data-driven frameworks that improved key performance metrics by 35% across all departments

I am particularly drawn to opportunities where I can leverage my expertise in technology leadership, digital transformation, and strategic business development to drive sustainable growth and competitive advantage.

My leadership philosophy centers on building high-performing teams, fostering cultures of innovation, and delivering measurable business results. I bring a unique combination of technical depth, strategic acumen, and operational excellence that enables organizations to thrive in rapidly evolving markets.

I would welcome the opportunity to discuss how my executive experience and proven track record can contribute to your organization's continued success and growth objectives.

Thank you for your consideration.

Sincerely,
${orderData.firstName} ${orderData.lastName}

---
Executive Cover Letter Template
Generated by Neuro.Pilot.AI - Executive Package
Customizable for specific opportunities and organizations
        `.trim();

        const coverLetterPath = path.join(__dirname, 'generated_resumes', `${orderData.firstName}_${orderData.lastName}_Executive_Cover_Letter.txt`);
        fs.writeFileSync(coverLetterPath, coverLetterContent);
        
        console.log('📝 Executive Cover Letter Generated');
        return coverLetterPath;
    }

    async sendExecutiveEmail(orderData, resumeFiles, coverLetterPath) {
        const emailHTML = `
<!DOCTYPE html>
<html>
<head>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
        
        body { 
            font-family: 'Inter', sans-serif; 
            line-height: 1.6; 
            color: #2c3e50; 
            margin: 0; 
            padding: 0; 
        }
        
        .container { 
            max-width: 700px; 
            margin: 0 auto; 
            background: #ffffff;
        }
        
        .header { 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            color: white; 
            padding: 40px 30px; 
            text-align: center; 
        }
        
        .header h1 {
            font-size: 32px;
            font-weight: 800;
            margin: 0 0 10px 0;
        }
        
        .header p {
            font-size: 16px;
            opacity: 0.9;
            margin: 0;
        }
        
        .content { 
            padding: 40px 30px; 
            background: #f8f9fa; 
        }
        
        .success-banner {
            background: linear-gradient(135deg, #48bb78, #38a169);
            color: white;
            padding: 25px;
            border-radius: 12px;
            text-align: center;
            margin-bottom: 30px;
        }
        
        .success-banner h2 {
            margin: 0 0 10px 0;
            font-size: 24px;
            font-weight: 700;
        }
        
        .order-summary {
            background: white;
            padding: 25px;
            border-radius: 12px;
            margin-bottom: 25px;
            border: 1px solid #e9ecef;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }
        
        .detail-row {
            display: flex;
            justify-content: space-between;
            margin: 12px 0;
            padding: 8px 0;
            border-bottom: 1px solid #f1f3f4;
        }
        
        .detail-row:last-child {
            border-bottom: none;
        }
        
        .detail-label {
            font-weight: 600;
            color: #495057;
        }
        
        .detail-value {
            color: #667eea;
            font-weight: 500;
        }
        
        .features-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin: 30px 0;
        }
        
        .feature-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            border: 1px solid #e9ecef;
            text-align: center;
        }
        
        .feature-icon {
            font-size: 32px;
            margin-bottom: 10px;
        }
        
        .feature-title {
            font-weight: 600;
            margin-bottom: 8px;
            color: #2c3e50;
        }
        
        .attachments {
            background: #e8f5e9;
            border: 1px solid #c8e6c9;
            padding: 20px;
            border-radius: 10px;
            margin: 25px 0;
        }
        
        .attachment-item {
            display: flex;
            align-items: center;
            gap: 10px;
            margin: 8px 0;
            font-weight: 500;
        }
        
        .next-steps {
            background: white;
            padding: 25px;
            border-radius: 12px;
            border: 1px solid #e9ecef;
            margin: 25px 0;
        }
        
        .footer {
            background: #2c3e50;
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .cta-button {
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            padding: 12px 25px;
            text-decoration: none;
            border-radius: 8px;
            font-weight: 600;
            display: inline-block;
            margin: 15px 10px;
        }
        
        .highlight {
            background: #fff3cd;
            padding: 15px;
            border-radius: 8px;
            border-left: 4px solid #ffc107;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎉 Executive Package Complete!</h1>
            <p>Your Premium AI-Optimized Resume Suite is Ready</p>
        </div>
        
        <div class="content">
            <div class="success-banner">
                <h2>✅ Order Successfully Completed</h2>
                <p>Professional executive-level resume generated with advanced AI optimization</p>
            </div>
            
            <div class="order-summary">
                <h3 style="color: #2c3e50; margin-bottom: 20px;">📋 Order Summary</h3>
                
                <div class="detail-row">
                    <span class="detail-label">Order ID:</span>
                    <span class="detail-value">${orderData.orderId}</span>
                </div>
                
                <div class="detail-row">
                    <span class="detail-label">Package:</span>
                    <span class="detail-value">Executive Premium</span>
                </div>
                
                <div class="detail-row">
                    <span class="detail-label">Customer:</span>
                    <span class="detail-value">${orderData.firstName} ${orderData.lastName}</span>
                </div>
                
                <div class="detail-row">
                    <span class="detail-label">Original Price:</span>
                    <span class="detail-value">$${orderData.originalPrice}</span>
                </div>
                
                <div class="detail-row">
                    <span class="detail-label">Promo Applied:</span>
                    <span class="detail-value">${orderData.promoCode} (100% OFF)</span>
                </div>
                
                <div class="detail-row">
                    <span class="detail-label">Final Price:</span>
                    <span class="detail-value" style="color: #48bb78; font-weight: 700;">FREE</span>
                </div>
                
                <div class="detail-row">
                    <span class="detail-label">Processing Time:</span>
                    <span class="detail-value">Completed in under 1 hour</span>
                </div>
            </div>
            
            <div class="highlight">
                <strong>🚀 Upgrade Notice:</strong> We've significantly improved our AI resume generator since your original order. 
                This redelivery includes our latest executive-level templates and professional formatting!
            </div>
            
            <div class="features-grid">
                <div class="feature-card">
                    <div class="feature-icon">🎯</div>
                    <div class="feature-title">Executive Positioning</div>
                    <p>C-suite level accomplishments and strategic leadership focus</p>
                </div>
                
                <div class="feature-card">
                    <div class="feature-icon">📊</div>
                    <div class="feature-title">Quantified Achievements</div>
                    <p>Measurable results with financial impact and performance metrics</p>
                </div>
                
                <div class="feature-card">
                    <div class="feature-icon">🔧</div>
                    <div class="feature-title">ATS Optimized</div>
                    <p>Keyword optimized for Applicant Tracking Systems</p>
                </div>
                
                <div class="feature-card">
                    <div class="feature-icon">💼</div>
                    <div class="feature-title">Professional Design</div>
                    <p>Executive-level formatting with multiple export formats</p>
                </div>
            </div>
            
            <div class="attachments">
                <h3 style="margin: 0 0 15px 0; color: #2c3e50;">📎 Package Contents</h3>
                
                <div class="attachment-item">
                    <span>📄</span>
                    <span><strong>Executive Resume (HTML)</strong> - Professional web-optimized format</span>
                </div>
                
                <div class="attachment-item">
                    <span>📝</span>
                    <span><strong>Executive Resume (Text)</strong> - ATS-compatible plain text</span>
                </div>
                
                <div class="attachment-item">
                    <span>✉️</span>
                    <span><strong>Executive Cover Letter</strong> - Customizable template</span>
                </div>
            </div>
            
            <div class="next-steps">
                <h3 style="color: #2c3e50; margin-bottom: 15px;">🚀 How to Use Your Executive Resume</h3>
                
                <ol style="color: #495057; line-height: 1.8;">
                    <li><strong>Review for Accuracy:</strong> Customize company names, dates, and specific achievements</li>
                    <li><strong>Tailor for Applications:</strong> Adjust keywords based on specific job descriptions</li>
                    <li><strong>Use HTML Version:</strong> For online applications and LinkedIn profile updates</li>
                    <li><strong>Use Text Version:</strong> For ATS systems and email submissions</li>
                    <li><strong>Customize Cover Letter:</strong> Adapt the template for specific opportunities</li>
                </ol>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
                <h3 style="color: #2c3e50;">Need Revisions?</h3>
                <p>Reply to this email within 7 days for free modifications</p>
                <a href="mailto:neuro.pilot.ai@gmail.com?subject=Resume Revision Request - ${orderData.orderId}" class="cta-button">
                    Request Revisions
                </a>
            </div>
            
            <div style="text-align: center; background: #f8f9fa; padding: 20px; border-radius: 10px; margin: 25px 0;">
                <h4 style="color: #2c3e50; margin-bottom: 10px;">🌟 Thank You for Choosing Neuro.Pilot.AI</h4>
                <p style="color: #6c757d; margin: 0;">Your success is our mission. Best of luck with your executive opportunities!</p>
            </div>
        </div>
        
        <div class="footer">
            <h3>Neuro.Pilot.AI</h3>
            <p>Advanced AI-Powered Resume Optimization</p>
            <p style="font-size: 14px; opacity: 0.8;">
                Order delivered on ${new Date().toLocaleString()}<br>
                Professional AI Resume Generation System v2.0
            </p>
        </div>
    </div>
</body>
</html>
        `;

        const mailOptions = {
            from: '"Neuro.Pilot.AI Executive Services" <neuro.pilot.ai@gmail.com>',
            to: orderData.email,
            subject: `🎉 Your Executive Resume Package is Ready! - Premium Redelivery`,
            html: emailHTML,
            attachments: [
                {
                    filename: 'David_Mikulis_Executive_Resume.html',
                    path: resumeFiles.htmlPath,
                    contentType: 'text/html'
                },
                {
                    filename: 'David_Mikulis_Executive_Resume.txt',
                    path: resumeFiles.textPath,
                    contentType: 'text/plain'
                },
                {
                    filename: 'David_Mikulis_Executive_Cover_Letter.txt',
                    path: coverLetterPath,
                    contentType: 'text/plain'
                }
            ]
        };

        try {
            const info = await this.transporter.sendMail(mailOptions);
            console.log('✅ Executive Package Email Sent Successfully!');
            console.log('📧 Message ID:', info.messageId);
            console.log('📫 Delivered to:', orderData.email);
            
            return { success: true, messageId: info.messageId };
        } catch (error) {
            console.error('❌ Email send error:', error);
            return { success: false, error: error.message };
        }
    }
}

// Execute the delivery
async function main() {
    console.log('🚀 EXECUTIVE PACKAGE REDELIVERY');
    console.log('═'.repeat(50));
    
    const delivery = new ExecutivePackageDelivery();
    await delivery.sendExecutivePackage();
    
    console.log('═'.repeat(50));
    console.log('🎯 DELIVERY COMPLETE!');
    console.log('📧 Check david.mikulis66@gmail.com for the executive package');
    console.log('💼 Professional-quality resume with executive positioning');
    console.log('📄 Multiple formats: HTML + Text + Cover Letter');
}

main().catch(console.error);