#!/usr/bin/env node

/**
 * Interactive .env Setup Script
 */

const fs = require('fs');
const readline = require('readline');
const path = require('path');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

async function setupEnvironment() {
    console.log('🔧 Neuro-Pilot-AI Environment Setup\n');
    console.log('This will help you configure your API keys.\n');

    const config = {};

    // Notion Setup
    console.log('1️⃣ NOTION SETUP');
    console.log('Go to: https://developers.notion.com/my-integrations');
    console.log('Create an integration and copy the token\n');
    
    config.NOTION_TOKEN = await question('Enter your Notion token (starts with secret_): ');
    config.NOTION_PARENT_PAGE_ID = await question('Enter your Notion parent page ID: ');

    // OpenAI Setup
    console.log('\n2️⃣ OPENAI SETUP');
    console.log('Go to: https://platform.openai.com/api-keys');
    console.log('Create a new API key\n');
    
    config.OPENAI_API_KEY = await question('Enter your OpenAI API key (starts with sk-): ');

    // Stripe Setup
    console.log('\n3️⃣ STRIPE SETUP');
    console.log('Go to: https://dashboard.stripe.com/test/apikeys');
    console.log('Copy your test keys\n');
    
    config.STRIPE_SECRET_KEY = await question('Enter your Stripe secret key (starts with sk_test_): ');
    config.STRIPE_PUBLISHABLE_KEY = await question('Enter your Stripe publishable key (starts with pk_test_): ');

    // Email Setup (optional)
    console.log('\n4️⃣ EMAIL SETUP (optional - press Enter to skip)');
    config.EMAIL_USER = await question('Enter your email address: ') || 'your_email@gmail.com';
    config.EMAIL_PASS = await question('Enter your email app password: ') || 'your_app_password';

    // Generate .env content
    const envContent = `# Neuro-Pilot-AI Environment Variables
# Generated by setup script

# Application Configuration
PORT=3001
NODE_ENV=development
WEBHOOK_PORT=3000

# Notion Integration
NOTION_TOKEN=${config.NOTION_TOKEN}
NOTION_PARENT_PAGE_ID=${config.NOTION_PARENT_PAGE_ID}
NOTION_RESUME_DATABASE_ID=to_be_generated
NOTION_TEMPLATE_DATABASE_ID=to_be_generated

# OpenAI Configuration
OPENAI_API_KEY=${config.OPENAI_API_KEY}

# Stripe Payment Processing
STRIPE_SECRET_KEY=${config.STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${config.STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=to_be_configured

# Email Configuration
EMAIL_USER=${config.EMAIL_USER}
EMAIL_PASS=${config.EMAIL_PASS}
EMAIL_FROM=noreply@yourdomain.com

# Other Configuration
NGROK_AUTH_TOKEN=your_ngrok_auth_token_here
JWT_SECRET=your_jwt_secret_${Date.now()}
ENCRYPTION_KEY=your_32_char_key_${Date.now()}
FRONTEND_URL=http://localhost:3001
LOG_LEVEL=info
ENABLE_ANALYTICS=true
`;

    // Backup existing .env if it exists
    if (fs.existsSync('.env')) {
        fs.renameSync('.env', `.env.backup.${Date.now()}`);
        console.log('\n📁 Backed up existing .env file');
    }

    // Write new .env file
    fs.writeFileSync('.env', envContent);
    console.log('\n✅ Created new .env file with your API keys!');
    
    rl.close();
    
    // Test the configuration
    console.log('\n🧪 Testing your configuration...\n');
    require('child_process').execSync('node test-all-apis.js', { stdio: 'inherit' });
}

setupEnvironment().catch(error => {
    console.error('❌ Setup failed:', error);
    rl.close();
});