# Render Blueprint for NEURO.PILOT.AI Inventory System
services:
  - type: web
    name: neuro-pilot-inventory
    runtime: node
    repo: https://github.com/davidmikulis/neuro-pilot-ai
    branch: main
    rootDir: backend
    buildCommand: npm ci --only=production
    startCommand: node inventory-complete-bilingual.js
    
    # Environment Configuration
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8083
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: david.mikulis@camp-inventory.com
      - key: ADMIN_PASSWORD
        value: inventory2025
        
    # Health and Performance
    healthCheckPath: /
    plan: starter # Use starter for always-on availability
    
    # Resource Configuration
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 80
      targetMemoryPercent: 80
    
    # Disk Storage for Inventory Data
    disk:
      name: inventory-data
      mountPath: /app/data
      sizeGB: 1

  # Optional: Database service (if needed for future expansion)
  - type: pserv
    name: inventory-database
    runtime: postgres
    plan: free
    databaseName: inventory_db
    databaseUser: inventory_user
    ipAllowList: [] # Allow all IPs or specify allowed ranges

# Static Assets (if needed)
staticSites:
  - name: inventory-assets
    buildCommand: echo "No build needed for static assets"
    publishPath: backend/public
    pullRequestPreviewsEnabled: false