version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./.env
    ports:
      - "3001:3001"
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
