-- ============================================================================
-- Finance AI Audit Log (v15.4.0)
-- Tracks all AI-generated queries, SQL, and exports for governance
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_finance_audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TEXT NOT NULL DEFAULT (datetime('now')),
  user TEXT NOT NULL,
  role TEXT NOT NULL,
  question TEXT,  -- User's natural language question
  tool TEXT,      -- Tool invoked: runPivot, exportReport, explainVariance
  params TEXT,    -- JSON params passed to tool
  generated_sql TEXT,  -- SQL generated by AI (for transparency)
  rowcount INTEGER DEFAULT 0,
  export_uri TEXT,  -- S3/local path if exported
  duration_ms INTEGER DEFAULT 0,
  status TEXT DEFAULT 'success',  -- success, error, blocked
  error_msg TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_finance_audit_ts ON ai_finance_audit(ts);
CREATE INDEX IF NOT EXISTS idx_ai_finance_audit_user ON ai_finance_audit(user);
CREATE INDEX IF NOT EXISTS idx_ai_finance_audit_tool ON ai_finance_audit(tool);
CREATE INDEX IF NOT EXISTS idx_ai_finance_audit_status ON ai_finance_audit(status);

-- Export schedules (for recurring reports)
CREATE TABLE IF NOT EXISTS finance_export_schedules (
  schedule_id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  cron TEXT NOT NULL,  -- e.g., "0 9 * * MON"
  params TEXT NOT NULL,  -- JSON: {format, period, groupBy, filters}
  recipients TEXT,  -- JSON array of emails
  enabled INTEGER DEFAULT 1,
  last_run TEXT,
  next_run TEXT,
  created_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_finance_schedule_enabled ON finance_export_schedules(enabled);
CREATE INDEX IF NOT EXISTS idx_finance_schedule_next ON finance_export_schedules(next_run);

-- Data quality issues (for monitoring)
CREATE TABLE IF NOT EXISTS finance_data_quality_issues (
  issue_id INTEGER PRIMARY KEY AUTOINCREMENT,
  issue_type TEXT NOT NULL,  -- duplicate_invoice, missing_category, negative_amount, etc.
  severity TEXT DEFAULT 'warning',  -- info, warning, critical
  entity_type TEXT,  -- invoice, vendor, category
  entity_id TEXT,
  description TEXT,
  detected_at TEXT DEFAULT (datetime('now')),
  resolved_at TEXT,
  resolved_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_finance_dq_type ON finance_data_quality_issues(issue_type);
CREATE INDEX IF NOT EXISTS idx_finance_dq_resolved ON finance_data_quality_issues(resolved_at);
