# ================================================================
# NeuroPilot v17.3 - AI Ops Configuration
# ================================================================
# Configuration for autonomous infrastructure optimization
# ================================================================

# API Credentials (use environment variables in production)
grafana_url: "${GRAFANA_URL}"
grafana_api_key: "${GRAFANA_API_KEY}"
prometheus_url: "${PROMETHEUS_URL:-http://localhost:9090}"

notion_api_key: "${NOTION_API_KEY}"
notion_database_id: "${NOTION_DATABASE_ID}"

slack_webhook_url: "${SLACK_WEBHOOK_URL}"

# Terraform Configuration
terraform_path: "./infrastructure/terraform"

# Alert Thresholds (auto-tuned by AI)
alert_thresholds:
  latency_ms: 150
  error_rate: 2.0
  cpu_usage: 70.0
  memory_usage: 75.0

# Anomaly Detection Settings
anomaly_sensitivity: 0.92  # 0.0 (low) to 1.0 (high)
anomaly_detection:
  zscore_threshold: 3.0
  ewma_span: 20
  seasonal_period: 24  # hours

# AI Learning Configuration
learning:
  enabled: true
  learning_rate: 0.01
  reward_function: "sla_compliance - cost_variance"
  exploration_rate: 0.1  # epsilon for exploration

# SLA and Cost Targets
sla_target: 99.95  # percentage
cost_budget: 50.0  # USD per month
cost_warning_threshold: 0.8  # 80% of budget
cost_critical_threshold: 0.96  # 96% of budget

# Auto-Scaling Configuration
auto_scaling:
  enabled: true
  min_instances: 1
  max_instances: 5
  scale_up_cooldown: 300  # 5 minutes
  scale_down_cooldown: 600  # 10 minutes
  scale_up_threshold:
    cpu: 80
    memory: 80
    latency: 400
  scale_down_threshold:
    cpu: 30
    memory: 30
    latency: 100

# Reporting Configuration
reporting:
  daily_report_time: "09:00"  # UTC
  weekly_summary: true
  monthly_summary: true
  include_recommendations: true
  max_recommendations: 5

# Model Configuration
model:
  type: "GaussianMixture"
  n_components: 3
  covariance_type: "full"
  max_iter: 100
  retrain_interval_hours: 24
  min_training_samples: 48

# Logging Configuration
logging:
  level: "INFO"
  log_file: "/var/log/neuropilot/ops_brain.log"
  max_log_size_mb: 100
  backup_count: 5

# Feature Flags
features:
  autonomous_scaling: true
  autonomous_threshold_tuning: true
  predictive_alerts: false  # coming soon
  cost_optimization: true
  anomaly_detection: true
