#!/bin/bash
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluLTEiLCJlbWFpbCI6Im5ldXJvcGlsb3RhaUBnbWFpbC5jb20iLCJyb2xlIjoib3duZXIiLCJwZXJtaXNzaW9ucyI6WyJpbnZlbnRvcnk6cmVhZCIsImludmVudG9yeTp3cml0ZSIsImludmVudG9yeTpkZWxldGUiLCJpbnZlbnRvcnk6Y291bnQiLCJpbnZlbnRvcnk6YXBwcm92ZSIsIm9yZGVyczpyZWFkIiwib3JkZXJzOndyaXRlIiwib3JkZXJzOmRlbGV0ZSIsInVzZXJzOnJlYWQiLCJ1c2Vyczp3cml0ZSIsInVzZXJzOmRlbGV0ZSIsInJlcG9ydHM6cmVhZCIsImF1ZGl0OnJlYWQiLCJzZXR0aW5nczp3cml0ZSIsInN5c3RlbTphZG1pbiIsIm93bmVyOmNvbnNvbGUiXSwiaWF0IjoxNzYwMTU2MjU1LCJleHAiOjE3NjAxNTcxNTUsImF1ZCI6ImludmVudG9yeS11c2VycyIsImlzcyI6Im5ldXJvLXBpbG90LWludmVudG9yeSJ9.KhQLxm-8WFg4a_uD15Aau03RRp0iARDy2Cftt-aSwmM"

echo "Testing PDF API..."
curl -s "http://localhost:8083/api/owner/pdfs?limit=2" -H "Authorization: Bearer $TOKEN"
